import { Figure } from '../Figure'
import { MEASURED as M } from '../measured'

/**
 * "the work" — the engineering evidence at the foot of the case study. Every number is REAL: it is
 * read from src/case/measured.ts, which is itself generated by running the shipping engines 500
 * seeds at a time and capturing the vitest run (see scripts/emit-case-data.ts). So the page never
 * claims a figure it did not measure. The charts sit on the same cream figure cards as the live
 * demos above, the bright counter-rhythm to the slate prose.
 */

const SLATE = '#5d646b'
const STEEL = '#4e6a7a'
const CREAM_INK = '#5d646b'

interface Bar {
  label: string
  /** 0..1 fill fraction of the track */
  fill: number
  /** the printed readout */
  read: string
  /** optional accent for this bar */
  tone?: string
}

export function WorkShown() {
  const g = M.grid
  const p = M.palette
  const maxLen = Math.max(...g.programLen)
  return (
    <section aria-labelledby="data-h" style={{ margin: 'clamp(48px, 10vw, 104px) 0 0' }}>
      <div style={{ fontFamily: 'var(--font-mono)', fontSize: 11, letterSpacing: '0.18em', color: '#a6bac6', marginBottom: 16 }}>
        the work
      </div>
      <h2
        id="data-h"
        style={{
          margin: 0,
          fontFamily: 'var(--font-display)',
          fontWeight: 400,
          fontSize: 'clamp(26px, 4.6vw, 40px)',
          lineHeight: 1.12,
          letterSpacing: '-0.01em',
          maxWidth: '22ch',
        }}
      >
        the part where i show my work
      </h2>
      <p style={{ margin: '20px 0 0', maxWidth: '64ch', fontFamily: 'var(--font-display)', fontSize: 'clamp(16px, 2.1vw, 18px)', lineHeight: 1.62, color: '#f4f0e8', opacity: 0.86 }}>
        none of this is vibes. every figure below was computed by running the shipping engines {M.seeds} seeds
        at a time and reading the distribution, then captured straight from the test run. if it says 100
        percent, i counted all of it.
      </p>
      <p style={{ margin: '10px 0 0', fontFamily: 'var(--font-mono)', fontSize: 11.5, color: '#f4f0e8', opacity: 0.5 }}>
        {M.tests.total} tests across {M.tests.suites} files, all green · regenerated {M.generatedAt} from commit {M.commit}
      </p>

      <Crosshairs
        title="what the invariant suite proves"
        items={[
          'zero gaps, zero overlaps, every cell inside the canvas',
          'every guide sits bit-exact on a module edge (=== , not ≈)',
          'a mirrored grid reflects exactly, to one part in a billion',
          'every ratio label matches the proportion it actually measured',
          'color stays inside the screen’s gamut by construction, never by clipping',
        ]}
      />

      <div
        style={{
          marginTop: 'clamp(24px, 5vw, 40px)',
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
          gap: 'clamp(18px, 3vw, 28px)',
        }}
      >
        <Figure
          index="m1"
          title="tilings that hold"
          caption={`every one of ${M.seeds} seeds renders a perfect tiling, and the invariant suite re-checks it across 27 dial settings × 25 seeds. correctness is a property of how the grid is grown, not a test i got lucky on; the tests just keep me honest.`}
        >
          <Stat big={`${g.validRate}%`} sub={`valid tilings, ${M.seeds} seeds`} />
        </Figure>

        <Figure
          index="m2"
          title="build programs"
          caption="a composition is an ordered chain of one to four stages. most stay short; the long body plans are the rare, weird, lovely ones."
        >
          <Bars
            bars={g.programLen.map((c, i) => ({ label: `${i + 1} stage${i ? 's' : ''}`, fill: c / maxLen, read: `${Math.round((100 * c) / M.seeds)}%` }))}
          />
        </Figure>

        <Figure
          index="m3"
          title="coordinated stages emerge"
          caption="the cut programs randomness can never wander into, kept a deliberate minority so no single look takes over the output."
        >
          <Bars
            bars={[
              { label: 'lattice', fill: g.stages.lattice / 30, read: `${g.stages.lattice}%` },
              { label: 'spiral', fill: g.stages.spiral / 30, read: `${g.stages.spiral}%` },
              { label: 'echo', fill: g.stages.echo / 30, read: `${g.stages.echo}%` },
              { label: 'mirror', fill: g.stages.mirror / 30, read: `${g.stages.mirror}%` },
            ]}
          />
        </Figure>

        <Figure
          index="m4"
          title="where the lead color lands"
          caption="share of palettes whose hero color is magenta or violet. scoring vividness on absolute chroma quietly funneled everything into the deepest-gamut corner; scoring it against each hue’s own ceiling fixed it. yes, i had made every palette purple and not noticed."
        >
          <Bars
            bars={[
              { label: 'absolute chroma', fill: p.heroMagentaBefore / 100, read: `${p.heroMagentaBefore}%`, tone: '#a24fb8' },
              { label: 'relative (now)', fill: p.heroMagentaNow / 100, read: `${p.heroMagentaNow}%`, tone: '#a24fb8' },
            ]}
          />
        </Figure>

        <Figure
          index="m5"
          title="palette looks reachable"
          caption="share of 500 seeds landing in each recognizable look. not one is hard-coded; each emerges from the same continuous axes and has to survive selection to show up."
        >
          <Bars
            bars={[
              { label: 'spread hue', fill: p.genre.spreadHue / 36, read: `${p.genre.spreadHue}%` },
              { label: 'tight / mono', fill: p.genre.tightHue / 36, read: `${p.genre.tightHue}%` },
              { label: 'neon / jewel', fill: p.genre.neonJewel / 36, read: `${p.genre.neonJewel}%` },
              { label: 'high-key pastel', fill: p.genre.highKey / 36, read: `${p.genre.highKey}%` },
              { label: 'low-key moody', fill: p.genre.lowKey / 36, read: `${p.genre.lowKey}%` },
              { label: 'figure-ground', fill: p.genre.figureGround / 36, read: `${p.genre.figureGround}%` },
            ]}
          />
        </Figure>

        <Figure
          index="m6"
          title="the worst seed, not the average"
          caption="anyone can make a nice average. the real bar is the single worst draw out of five hundred, and the spread of distinct shapes that says it never collapses onto one safe answer."
        >
          <Bars
            bars={[
              { label: 'palette floor', fill: p.scoreMin, read: p.scoreMin.toFixed(2) },
              { label: 'grid floor', fill: g.scoreMin, read: g.scoreMin.toFixed(2) },
              { label: 'distinct grids', fill: g.distinctShapes / M.seeds, read: `${g.distinctShapes}/${M.seeds}` },
              { label: 'most common shape', fill: g.topAttractor / 100, read: `${g.topAttractor}%` },
            ]}
          />
        </Figure>
      </div>
    </section>
  )
}

/** A crosshair (+) list, the case study's bullet replacement. */
function Crosshairs({ title, items }: { title: string; items: string[] }) {
  return (
    <div style={{ marginTop: 'clamp(24px, 4vw, 36px)', maxWidth: '64ch' }}>
      <div style={{ fontFamily: 'var(--font-mono)', fontSize: 11, letterSpacing: '0.12em', color: '#a6bac6', marginBottom: 12 }}>
        {title}
      </div>
      <ul style={{ margin: 0, padding: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 8 }}>
        {items.map((it, i) => (
          <li key={i} style={{ display: 'flex', gap: 12, fontFamily: 'var(--font-mono)', fontSize: 12.5, lineHeight: 1.5, color: '#f4f0e8' }}>
            <span aria-hidden style={{ color: '#a6bac6', opacity: 0.8 }}>+</span>
            <span style={{ opacity: 0.82 }}>{it}</span>
          </li>
        ))}
      </ul>
    </div>
  )
}

/** A big number + sub-caption, slate ink on the cream figure card. */
function Stat({ big, sub }: { big: string; sub: string }) {
  return (
    <div>
      <div style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(52px, 10vw, 80px)', lineHeight: 1, letterSpacing: '-0.02em', color: SLATE }}>
        {big}
      </div>
      <div style={{ marginTop: 10, fontFamily: 'var(--font-mono)', fontSize: 11.5, color: STEEL, letterSpacing: '0.03em' }}>
        {sub}
      </div>
    </div>
  )
}

/** Horizontal bars, slate/steel on the cream figure card. */
function Bars({ bars }: { bars: Bar[] }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
      {bars.map((b, i) => (
        <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <span style={{ flex: '0 0 104px', fontFamily: 'var(--font-mono)', fontSize: 11, color: CREAM_INK, opacity: 0.8, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
            {b.label}
          </span>
          <span style={{ flex: 1, height: 7, background: 'rgba(93,100,107,0.16)', position: 'relative' }}>
            <span style={{ position: 'absolute', inset: '0 auto 0 0', width: `${Math.max(0, Math.min(1, b.fill)) * 100}%`, background: b.tone ?? STEEL }} />
          </span>
          <span style={{ flex: '0 0 52px', textAlign: 'right', fontFamily: 'var(--font-mono)', fontSize: 11, color: SLATE }}>
            {b.read}
          </span>
        </div>
      ))}
    </div>
  )
}
